/**
 * PI管理相关类型定义
 */

// PI状态
export interface PIStatus {
  planningStatus: 'draft' | 'confirmed' | 'finalized'
  piPlanningStatus: 'not-started' | 'in-progress' | 'completed'
  executionProgress: number
}

// PI中包含的版本
export interface PIIncludedVersion {
  versionId: string
  productId: string
  productName: string
  versionNumber: string
  completionPercentage: number
  storyPoints: number
  iterationRange: string
}

// PI里程碑对齐
export interface PIMilestone {
  milestoneId: string
  milestoneName: string
  targetDate: string
}

// PI
export interface PI {
  piId: string
  piNumber: string
  piName: string
  
  // 时间范围
  startDate: string
  endDate: string
  startIterationNumber: number
  endIterationNumber: number
  iterationCount: number
  durationWeeks: number
  
  // 里程碑对齐
  alignedMilestone: PIMilestone
  milestoneGap: number  // PI结束日期与里程碑目标日期之间的天数差
  alignmentStatus: 'good' | 'tight' | 'risk'
  
  // 包含的版本
  includedVersions: PIIncludedVersion[]
  
  // Epic和Feature范围
  epicIds: string[]
  epicCount: number
  totalStoryPoints: number
  estimatedFeatures: number
  
  // 状态
  status: PIStatus
  
  // 元数据
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

// 创建PI输入
export interface CreatePIInput {
  piNumber: string
  piName: string
  startIterationNumber: number
  endIterationNumber: number
  alignedMilestoneId: string
  includedVersionIds: string[]
}

// 更新PI输入
export interface UpdatePIInput {
  piId: string
  piName?: string
  startIterationNumber?: number
  endIterationNumber?: number
  alignedMilestoneId?: string
  status?: PIStatus
}

// PI筛选条件
export interface PIFilter {
  projectId?: string
  alignedMilestoneId?: string
  planningStatus?: string
}

// PI生成配置
export interface PIGenerateConfig {
  projectId: string
  milestones: Array<{
    milestoneId: string
    milestoneName: string
    targetDate: string
    iterationNumber: number
  }>
  versions: Array<{
    versionId: string
    productName: string
    versionNumber: string
    startIterationNumber: number
    endIterationNumber: number
    alignedMilestoneId: string
    totalStoryPoints: number
  }>
}

// PI生成结果
export interface PIGenerateResult {
  success: boolean
  generatedPIs: PI[]
  message: string
}
